-- Insert store types
INSERT INTO
    "types" (name, description)
VALUES ('Repair',
        'Repair and maintenance services'),
       ('Second-Hand',
        'Pre-owned and vintage items'),
       ('Clothing',
        'Sustainable clothing and apparel'),
       ('Footwear',
        'Eco-friendly shoes and footwear'),
       ('Accessories',
        'Sustainable fashion accessories'),
       ('Grocery',
        'Organic and sustainable food products'),
       ('Specialty Food & Drink',
        'Artisanal food and beverages'),
       ('Home Goods',
        'Sustainable household items'),
       ('Hardware & Garden',
        'Eco-friendly hardware and garden supplies'),
       ('Pet Supplies',
        'Sustainable pet care products'),
       ('Book & Media',
        'Books and media content'),
       ('Hobby & Toy',
        'Sustainable toys and hobby items'),
       ('Health & Beauty',
        'Natural health and beauty products'),
       ('General Merchandise',
        'Various sustainable products'),
       ('Service Provider',
        'Sustainable services'),
       ('Bags & Luggage',
        'Eco-friendly bags and luggage'),
       ('Jewelry',
        'Sustainable jewelry and accessories'),
       ('Electronics',
        'Eco-friendly electronic products'),
       ('Sports & Outdoor',
        'Sustainable sports and outdoor gear'),
       ('Art & Craft',
        'Sustainable art and craft supplies'),
       ('Office Supplies',
        'Eco-friendly office products'),
       ('Wellness & Fitness',
        'Sustainable wellness and fitness items'),
       ('Baby & Kids',
        'Sustainable products for children'),
       ('Decor',
        'Sustainable home decoration'),
       ('Gifts & Lifestyle',
        'Sustainable gifts and lifestyle products');

-- Insert statements
INSERT INTO
    statements ("statement")
VALUES (
        'Getting necessary data from the website...'
    ),
    (
        'Cosh eco is a platform for sustainable fashion and lifestyle brands.'
    ),
    (
        'Thank you for using cosh! :)'
    ),
    ('Loading...'),
    (
        'Fashion fades, style is eternal. - Yves Saint Laurent'
    ),
    (
        'Buy less, choose well, make it last. - Vivienne Westwood'
    ),
    (
        'Style is a way to say who you are without having to speak. - Rachel Zoe'
    ),
    (
        'Discovering eco-friendly brands...'
    ),
    (
        'Finding your next sustainable style...'
    ),
    (
        'Curating conscious choices for you...'
    ),
    (
        'Exploring ethical fashion...'
    ),
    (
        'Connecting you with sustainable living...'
    ),
    ('Adding the final touches...');

-- Insert locations from cosh.eco
INSERT INTO
    locations (
        street,
        number,
        postal_code,
        city,
        country
    )
VALUES (
        'Huidevettersstraat',
        '46',
        '2000',
        'Antwerp',
        'Belgium'
    ),
    (
        'Everdijstraat',
        '35',
        '2000',
        'Antwerp',
        'Belgium'
    ),
    (
        'Sint-Jorispoort',
        '21-23',
        '2000',
        'Antwerp',
        'Belgium'
    ),
    (
        'Nationalestraat',
        '81',
        '2000',
        'Antwerp',
        'Belgium'
    ),
    (
        'Schuttershofstraat',
        '9',
        '2000',
        'Antwerp',
        'Belgium'
    ),
    (
        'Vestingstraat',
        '10',
        '2018',
        'Antwerp',
        'Belgium'
    ),
    (
        'Groendalstraat',
        '15',
        '2000',
        'Antwerp',
        'Belgium'
    ),
    (
        'Kammenstraat',
        '27',
        '2000',
        'Antwerp',
        'Belgium'
    ),
    (
        'Kloosterstraat',
        '27',
        '2000',
        'Antwerp',
        'Belgium'
    ),
    (
        'Leopoldstraat',
        '3',
        '2000',
        'Antwerp',
        'Belgium'
    );

-- Insert stores from cosh.eco
INSERT INTO
    stores (
        name,
        description,
        location_id,
        retour
    )
VALUES (
        'STAY',
        'Sustainable fashion and lifestyle store',
        1,
        'Returns accepted within 14 days with receipt.'
    ),
    (
        'Lisa Ray',
        'Conscious fashion boutique',
        2,
        'Items can be returned within 30 days in original condition.'
    ),
    (
        'Atelier Beau',
        'Sustainable fashion concept store',
        3,
        'No returns on sale items. Standard returns within 14 days.'
    ),
    (
        'Supergoods',
        'Eco-friendly fashion and lifestyle',
        4,
        'Return unworn items within 21 days for a refund.'
    ),
    (
        'Het Strand',
        'Conscious fashion and swimwear',
        5,
        'Swimwear can only be returned if unworn and with tags.'
    ),
    (
        'Rewind Antwerp',
        'Second-hand luxury fashion',
        6,
        'Returns accepted within 7 days for store credit.'
    ),
    (
        'Clinic by CG',
        'Sustainable designer fashion',
        7,
        'Returns within 14 days. No returns on cosmetics.'
    ),
    (
        'ENES',
        'Ethical fashion and accessories',
        8,
        'Return within 14 days with original packaging.'
    ),
    (
        'UNIKOO',
        'Fair fashion boutique',
        9,
        'Returns accepted within 30 days. Items must be unused.'
    ),
    (
        'Just Hazel',
        'Sustainable fashion and gifts',
        10,
        'Gift items can be returned within 14 days with receipt.'
    );

-- Insert brands with cosh.eco labels
INSERT INTO
    brands (name, label)
VALUES ('STAY', 'A'),
    ('LRAY', 'B'),
    ('BEAU', 'A'),
    ('SGOOD', 'A'),
    ('STRAN', 'B'),
    ('REWIN', 'B'),
    ('CLINC', 'A'),
    ('ENES', 'B'),
    ('UNIKO', 'A'),
    ('HAZL', 'B');

-- Create store-brand relationships
INSERT INTO
    store_brands (store_id, brand_id)
SELECT s.id, b.id
FROM stores s
    CROSS JOIN brands b
WHERE
    s.name LIKE '%' || substring(
        b.name
        from 1 for 3
    ) || '%';

-- Insert store types relationships
INSERT INTO
    store_types (store_id, "type_id")
SELECT s.id, t.id
FROM stores s
    CROSS JOIN "types" t;

-- Insert opening hours for each day including closed days and split schedules
-- Insert opening hours for each day including closed days and split schedules
INSERT INTO
    opening_hours (day,
                   openingAt,
                   closingAt,
                   openingAtAfterNoon,
                   closingAtAfterNoon,
                   store_id)
VALUES
    (
        'Monday',
        'closed',
        'closed',
        null,
        null,
        1
    ),
    (
        'Tuesday',
        '11:00',
        '18:00',
        null,
        null,
        1
    ),
    (
        'Wednesday',
        '11:00',
        '18:00',
        null,
        null,
        1
    ),
    (
        'Thursday',
        '11:00',
        '18:00',
        null,
        null,
        1
    ),
    (
        'Friday',
        '11:00',
        '18:00',
        null,
        null,
        1
    ),
    (
        'Saturday',
        '11:00',
        '18:00',
        null,
        null,
        1
    ),
    (
        'Sunday',
        'closed',
        'closed',
        null,
        null,
        1),
    -- Lisa Ray
    ('Monday',
     'closed',
     'closed',
     null,
     null,
     2),
    ('Tuesday',
     '10:00',
     '13:00',
     '14:00',
     '18:00',
     2),
    ('Wednesday',
     '10:00',
     '18:00',
     null,
     null,
     2),
    ('Thursday',
     '10:00',
     '18:00',
     null,
     null,
     2),
    ('Friday',
     '10:00',
     '18:00',
     null,
     null,
     2),
    ('Saturday',
     '10:00',
     '18:00',
     null,
     null,
     2),
    ('Sunday',
     'closed',
     'closed',
     null,
     null,
     2),
    -- Atelier Beau
    ('Monday',
     '11:00',
     '18:00',
     null,
     null,
     3),
    ('Tuesday',
     '11:00',
     '18:00',
     null,
     null,
     3),
    ('Wednesday',
     '11:00',
     '18:00',
     null,
     null,
     3),
    ('Thursday',
     '11:00',
     '18:00',
     null,
     null,
     3),
    ('Friday',
     '11:00',
     '18:00',
     null,
     null,
     3),
    ('Saturday',
     '11:00',
     '18:00',
     null,
     null,
     3),
    ('Sunday',
     'closed',
     'closed',
     null,
     null,
     3),
    -- Supergoods
    ('Monday',
     '10:30',
     '18:00',
     null,
     null,
     4),
    ('Tuesday',
     '10:30',
     '18:00',
     null,
     null,
     4),
    ('Wednesday',
     '10:30',
     '18:00',
     null,
     null,
     4),
    ('Thursday',
     '10:30',
     '18:00',
     null,
     null,
     4),
    ('Friday',
     '10:30',
     '18:00',
     null,
     null,
     4),
    ('Saturday',
     '10:30',
     '18:00',
     null,
     null,
     4),
    ('Sunday',
     'closed',
     'closed',
     null,
     null,
     4),
    -- Het Strand
    ('Monday',
     'closed',
     'closed',
     null,
     null,
     5),
    ('Tuesday',
     '10:00',
     '18:00',
     null,
     null,
     5),
    ('Wednesday',
     '10:00',
     '18:00',
     null,
     null,
     5),
    ('Thursday',
     '10:00',
     '18:00',
     null,
     null,
     5),
    ('Friday',
     '10:00',
     '18:00',
     null,
     null,
     5),
    ('Saturday',
     '10:00',
     '18:00',
     null,
     null,
     5),
    ('Sunday',
     'closed',
     'closed',
     null,
     null,
     5),
    -- Rewind Antwerp
    ('Monday',
     'closed',
     'closed',
     null,
     null,
     6),
    ('Tuesday',
     '11:00',
     '18:00',
     null,
     null,
     6),
    ('Wednesday',
     '11:00',
     '18:00',
     null,
     null,
     6),
    ('Thursday',
     '11:00',
     '18:00',
     null,
     null,
     6),
    ('Friday',
     '11:00',
     '18:00',
     null,
     null,
     6),
    ('Saturday',
     '11:00',
     '17:00',
     null,
     null,
     6),
    ('Sunday',
     'closed',
     'closed',
     null,
     null,
     6),
    -- Clinic by CG
    ('Monday',
     '10:00',
     '18:00',
     null,
     null,
     7),
    ('Tuesday',
     '10:00',
     '18:00',
     null,
     null,
     7),
    ('Wednesday',
     '10:00',
     '18:00',
     null,
     null,
     7),
    ('Thursday',
     '10:00',
     '18:00',
     null,
     null,
     7),
    ('Friday',
     '10:00',
     '18:00',
     null,
     null,
     7),
    ('Saturday',
     '10:00',
     '18:00',
     null,
     null,
     7),
    ('Sunday',
     'closed',
     'closed',
     null,
     null,
     7),
    -- ENES
    ('Monday',
     'closed',
     'closed',
     null,
     null,
     8),
    ('Tuesday',
     '11:00',
     '18:00',
     null,
     null,
     8),
    ('Wednesday',
     '11:00',
     '18:00',
     null,
     null,
     8),
    ('Thursday',
     '11:00',
     '18:00',
     null,
     null,
     8),
    ('Friday',
     '11:00',
     '18:00',
     null,
     null,
     8),
    ('Saturday',
     '11:00',
     '18:00',
     null,
     null,
     8),
    ('Sunday',
     'closed',
     'closed',
     null,
     null,
     8),
    -- UNIKOO
    ('Monday',
     'closed',
     'closed',
     null,
     null,
     9),
    ('Tuesday',
     '10:30',
     '18:00',
     null,
     null,
     9),
    ('Wednesday',
     '10:30',
     '18:00',
     null,
     null,
     9),
    ('Thursday',
     '10:30',
     '18:00',
     null,
     null,
     9),
    ('Friday',
     '10:30',
     '18:00',
     null,
     null,
     9),
    ('Saturday',
     '10:30',
     '18:00',
     null,
     null,
     9),
    ('Sunday',
     'closed',
     'closed',
     null,
     null,
     9),
    -- Just Hazel
    ('Monday',
     'closed',
     'closed',
     null,
     null,
     10),
    ('Tuesday',
     '11:00',
     '18:00',
     null,
     null,
     10),
    ('Wednesday',
     '11:00',
     '18:00',
     null,
     null,
     10),
    ('Thursday',
     '11:00',
     '18:00',
     null,
     null,
     10),
    ('Friday',
     '11:00',
     '18:00',
     null,
     null,
     10),
    ('Saturday',
     '11:00',
     '18:00',
     null,
     null,
     10),
    ('Sunday',
     'closed',
     'closed',
     null,
     null,
     10);